name: finemapping-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-dplyr=0.8.0.1
  - conda-forge::r-optparse=1.6.1
  - conda-forge::r-devtools=2.0.1
  - conda-forge::r-readr=1.3.1
  - conda-forge::r-purrr=0.3.2
  - conda-forge::r-tidyr=0.8.3
  - conda-forge::r-assertthat=0.2.1
  - conda-forge::r-matrixstats=0.55.0
  - conda-forge::r-expm=0.999_4
  - conda-forge::r-data.table=1.11.8
  - conda-forge::r-stringr=1.4.0
  - bioconda::tabix=0.2.6
  - bioconda::csvtk=0.18.2
  - bioconda::bcftools=1.10.2
  - bioconda::bioconductor-rsamtools=1.34.0
  - bioconda::bioconductor-summarizedexperiment=1.12.0